/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'invited' : IDL.Null,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserView = IDL.Record({
  'status' : UserStatus,
  'principal' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateBookingInput = IDL.Record({
  'clientName' : IDL.Text,
  'clientEmail' : IDL.Text,
  'timeSlotStart' : IDL.Int,
  'fileUrls' : IDL.Vec(ExternalBlob),
  'timeSlotEnd' : IDL.Int,
  'purpose' : IDL.Text,
  'linkId' : IDL.Text,
});
export const BusyInterval = IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int });
export const BookingView = IDL.Record({
  'isCancelled' : IDL.Bool,
  'managementToken' : IDL.Text,
  'bookingId' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'clientEmail' : IDL.Text,
  'timeSlotStart' : IDL.Int,
  'fileUrls' : IDL.Vec(ExternalBlob),
  'timeSlotEnd' : IDL.Int,
  'purpose' : IDL.Text,
  'linkId' : IDL.Text,
});
export const Duration = IDL.Variant({
  'min15' : IDL.Null,
  'min30' : IDL.Null,
  'min45' : IDL.Null,
  'min60' : IDL.Null,
});
export const BookingLinkInput = IDL.Record({
  'duration' : Duration,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const BookingLinkView = IDL.Record({
  'id' : IDL.Text,
  'duration' : Duration,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
});
export const TimeSlot = IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int });
export const GoogleCredentialStatus = IDL.Record({
  'expiresAt' : IDL.Opt(IDL.Int),
  'isExpired' : IDL.Bool,
  'hasCredentials' : IDL.Bool,
});
export const BusyOverride = IDL.Record({
  'slotEnd' : IDL.Int,
  'slotStart' : IDL.Int,
  'isBookable' : IDL.Bool,
  'linkId' : IDL.Text,
});
export const InviteInput = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptInvite' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : UserView, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'cancelBookingByToken' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'changeUserRole' : IDL.Func([IDL.Text, UserRole], [IDL.Bool], []),
  'createBooking' : IDL.Func(
      [CreateBookingInput, IDL.Vec(BusyInterval), IDL.Text],
      [BookingView],
      [],
    ),
  'createBookingLink' : IDL.Func([BookingLinkInput], [BookingLinkView], []),
  'deleteBookingLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'fetchGoogleCalendarFreeBusy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAppBaseUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getAvailableSlots' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(BusyInterval)],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getBookingByToken' : IDL.Func([IDL.Text], [IDL.Opt(BookingView)], ['query']),
  'getBookingLink' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BookingLinkView)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getGoogleCalendarCredentialStatus' : IDL.Func(
      [],
      [GoogleCredentialStatus],
      [],
    ),
  'getGoogleOAuthClientId' : IDL.Func([], [IDL.Text], []),
  'getMyUserInfo' : IDL.Func([], [IDL.Opt(UserView)], []),
  'getOverridesForLink' : IDL.Func([IDL.Text], [IDL.Vec(BusyOverride)], []),
  'hasGoogleCalendarCredentials' : IDL.Func([], [IDL.Bool], []),
  'inviteUser' : IDL.Func([InviteInput], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBookingLinks' : IDL.Func([], [IDL.Vec(BookingLinkView)], []),
  'listBookings' : IDL.Func([], [IDL.Vec(BookingView)], []),
  'listUsers' : IDL.Func([], [IDL.Vec(UserView)], []),
  'refreshGoogleCalendarCredentials' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'removeUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'rescheduleBookingByToken' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(BusyInterval), IDL.Text],
      [IDL.Variant({ 'ok' : BookingView, 'err' : IDL.Text })],
      [],
    ),
  'setAppBaseUrl' : IDL.Func([IDL.Text], [], []),
  'setBookingLinkActive' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
  'setGoogleCalendarCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'setGoogleOAuthClientId' : IDL.Func([IDL.Text], [], []),
  'setHostPrincipal' : IDL.Func([IDL.Principal], [], []),
  'setUsersAppBaseUrl' : IDL.Func([IDL.Text], [], []),
  'toggleBusyOverride' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingLink' : IDL.Func(
      [IDL.Text, BookingLinkInput],
      [IDL.Opt(BookingLinkView)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserStatus = IDL.Variant({ 'active' : IDL.Null, 'invited' : IDL.Null });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserView = IDL.Record({
    'status' : UserStatus,
    'principal' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateBookingInput = IDL.Record({
    'clientName' : IDL.Text,
    'clientEmail' : IDL.Text,
    'timeSlotStart' : IDL.Int,
    'fileUrls' : IDL.Vec(ExternalBlob),
    'timeSlotEnd' : IDL.Int,
    'purpose' : IDL.Text,
    'linkId' : IDL.Text,
  });
  const BusyInterval = IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int });
  const BookingView = IDL.Record({
    'isCancelled' : IDL.Bool,
    'managementToken' : IDL.Text,
    'bookingId' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'clientEmail' : IDL.Text,
    'timeSlotStart' : IDL.Int,
    'fileUrls' : IDL.Vec(ExternalBlob),
    'timeSlotEnd' : IDL.Int,
    'purpose' : IDL.Text,
    'linkId' : IDL.Text,
  });
  const Duration = IDL.Variant({
    'min15' : IDL.Null,
    'min30' : IDL.Null,
    'min45' : IDL.Null,
    'min60' : IDL.Null,
  });
  const BookingLinkInput = IDL.Record({
    'duration' : Duration,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const BookingLinkView = IDL.Record({
    'id' : IDL.Text,
    'duration' : Duration,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
  });
  const TimeSlot = IDL.Record({ 'end' : IDL.Int, 'start' : IDL.Int });
  const GoogleCredentialStatus = IDL.Record({
    'expiresAt' : IDL.Opt(IDL.Int),
    'isExpired' : IDL.Bool,
    'hasCredentials' : IDL.Bool,
  });
  const BusyOverride = IDL.Record({
    'slotEnd' : IDL.Int,
    'slotStart' : IDL.Int,
    'isBookable' : IDL.Bool,
    'linkId' : IDL.Text,
  });
  const InviteInput = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptInvite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : UserView, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'cancelBookingByToken' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'changeUserRole' : IDL.Func([IDL.Text, UserRole], [IDL.Bool], []),
    'createBooking' : IDL.Func(
        [CreateBookingInput, IDL.Vec(BusyInterval), IDL.Text],
        [BookingView],
        [],
      ),
    'createBookingLink' : IDL.Func([BookingLinkInput], [BookingLinkView], []),
    'deleteBookingLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'fetchGoogleCalendarFreeBusy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAppBaseUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getAvailableSlots' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(BusyInterval)],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getBookingByToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BookingView)],
        ['query'],
      ),
    'getBookingLink' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BookingLinkView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getGoogleCalendarCredentialStatus' : IDL.Func(
        [],
        [GoogleCredentialStatus],
        [],
      ),
    'getGoogleOAuthClientId' : IDL.Func([], [IDL.Text], []),
    'getMyUserInfo' : IDL.Func([], [IDL.Opt(UserView)], []),
    'getOverridesForLink' : IDL.Func([IDL.Text], [IDL.Vec(BusyOverride)], []),
    'hasGoogleCalendarCredentials' : IDL.Func([], [IDL.Bool], []),
    'inviteUser' : IDL.Func([InviteInput], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBookingLinks' : IDL.Func([], [IDL.Vec(BookingLinkView)], []),
    'listBookings' : IDL.Func([], [IDL.Vec(BookingView)], []),
    'listUsers' : IDL.Func([], [IDL.Vec(UserView)], []),
    'refreshGoogleCalendarCredentials' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'removeUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'rescheduleBookingByToken' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(BusyInterval), IDL.Text],
        [IDL.Variant({ 'ok' : BookingView, 'err' : IDL.Text })],
        [],
      ),
    'setAppBaseUrl' : IDL.Func([IDL.Text], [], []),
    'setBookingLinkActive' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Bool], []),
    'setGoogleCalendarCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'setGoogleOAuthClientId' : IDL.Func([IDL.Text], [], []),
    'setHostPrincipal' : IDL.Func([IDL.Principal], [], []),
    'setUsersAppBaseUrl' : IDL.Func([IDL.Text], [], []),
    'toggleBusyOverride' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingLink' : IDL.Func(
        [IDL.Text, BookingLinkInput],
        [IDL.Opt(BookingLinkView)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };