/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingLinkInput {
  'duration' : Duration,
  'name' : string,
  'description' : string,
}
export interface BookingLinkView {
  'id' : string,
  'duration' : Duration,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : bigint,
}
export interface BookingView {
  'isCancelled' : boolean,
  'managementToken' : string,
  'bookingId' : string,
  'clientName' : string,
  'createdAt' : bigint,
  'clientEmail' : string,
  'timeSlotStart' : bigint,
  'fileUrls' : Array<ExternalBlob>,
  'timeSlotEnd' : bigint,
  'purpose' : string,
  'linkId' : string,
}
export interface BusyInterval { 'end' : bigint, 'start' : bigint }
export interface BusyOverride {
  'slotEnd' : bigint,
  'slotStart' : bigint,
  'isBookable' : boolean,
  'linkId' : string,
}
export interface CreateBookingInput {
  'clientName' : string,
  'clientEmail' : string,
  'timeSlotStart' : bigint,
  'fileUrls' : Array<ExternalBlob>,
  'timeSlotEnd' : bigint,
  'purpose' : string,
  'linkId' : string,
}
export type Duration = { 'min15' : null } |
  { 'min30' : null } |
  { 'min45' : null } |
  { 'min60' : null };
export type ExternalBlob = Uint8Array;
export interface GoogleCredentialStatus {
  'expiresAt' : [] | [bigint],
  'isExpired' : boolean,
  'hasCredentials' : boolean,
}
export interface InviteInput {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export interface TimeSlot { 'end' : bigint, 'start' : bigint }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'invited' : null };
export interface UserView {
  'status' : UserStatus,
  'principal' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'email' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  /**
   * / Set the base URL used in management links sent to clients.
   */
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  /**
   * / Get the current app base URL (for debugging).
   */
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptInvite' : ActorMethod<
    [string],
    { 'ok' : UserView } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelBooking' : ActorMethod<[string], boolean>,
  'cancelBookingByToken' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'changeUserRole' : ActorMethod<[string, UserRole], boolean>,
  'createBooking' : ActorMethod<
    [CreateBookingInput, Array<BusyInterval>, string],
    BookingView
  >,
  'createBookingLink' : ActorMethod<[BookingLinkInput], BookingLinkView>,
  'deleteBookingLink' : ActorMethod<[string], boolean>,
  /**
   * / Set the base URL used in management links sent to clients.
   */
  'fetchGoogleCalendarFreeBusy' : ActorMethod<[string, string, string], string>,
  /**
   * / Get the current app base URL (for debugging).
   */
  'getAppBaseUrl' : ActorMethod<[], string>,
  'getAvailableSlots' : ActorMethod<
    [string, bigint, bigint, Array<BusyInterval>],
    Array<TimeSlot>
  >,
  'getBookingByToken' : ActorMethod<[string], [] | [BookingView]>,
  'getBookingLink' : ActorMethod<[string], [] | [BookingLinkView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getGoogleCalendarCredentialStatus' : ActorMethod<[], GoogleCredentialStatus>,
  'getGoogleOAuthClientId' : ActorMethod<[], string>,
  'getMyUserInfo' : ActorMethod<[], [] | [UserView]>,
  'getOverridesForLink' : ActorMethod<[string], Array<BusyOverride>>,
  'hasGoogleCalendarCredentials' : ActorMethod<[], boolean>,
  'inviteUser' : ActorMethod<[InviteInput], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBookingLinks' : ActorMethod<[], Array<BookingLinkView>>,
  'listBookings' : ActorMethod<[], Array<BookingView>>,
  'listUsers' : ActorMethod<[], Array<UserView>>,
  'refreshGoogleCalendarCredentials' : ActorMethod<
    [],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'removeUser' : ActorMethod<[string], boolean>,
  'rescheduleBookingByToken' : ActorMethod<
    [string, bigint, bigint, Array<BusyInterval>, string],
    { 'ok' : BookingView } |
      { 'err' : string }
  >,
  /**
   * / Set the base URL used in management links sent to clients.
   */
  'setAppBaseUrl' : ActorMethod<[string], undefined>,
  'setBookingLinkActive' : ActorMethod<[string, boolean], boolean>,
  'setGoogleCalendarCredentials' : ActorMethod<
    [string, string, bigint],
    undefined
  >,
  'setGoogleOAuthClientId' : ActorMethod<[string], undefined>,
  'setHostPrincipal' : ActorMethod<[Principal], undefined>,
  'setUsersAppBaseUrl' : ActorMethod<[string], undefined>,
  'toggleBusyOverride' : ActorMethod<
    [string, bigint, bigint, boolean],
    boolean
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingLink' : ActorMethod<
    [string, BookingLinkInput],
    [] | [BookingLinkView]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];