/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GoogleCredentialStatus {
    expiresAt?: bigint;
    isExpired: boolean;
    hasCredentials: boolean;
}
export interface BookingLinkView {
    id: string;
    duration: Duration;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
}
export interface TimeSlot {
    end: bigint;
    start: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface UserView {
    status: UserStatus;
    principal?: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CreateBookingInput {
    clientName: string;
    clientEmail: string;
    timeSlotStart: bigint;
    fileUrls: Array<ExternalBlob>;
    timeSlotEnd: bigint;
    purpose: string;
    linkId: string;
}
export interface BusyInterval {
    end: bigint;
    start: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BookingView {
    isCancelled: boolean;
    managementToken: string;
    bookingId: string;
    clientName: string;
    createdAt: bigint;
    clientEmail: string;
    timeSlotStart: bigint;
    fileUrls: Array<ExternalBlob>;
    timeSlotEnd: bigint;
    purpose: string;
    linkId: string;
}
export interface BookingLinkInput {
    duration: Duration;
    name: string;
    description: string;
}
export interface BusyOverride {
    slotEnd: bigint;
    slotStart: bigint;
    isBookable: boolean;
    linkId: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface InviteInput {
    name: string;
    role: UserRole;
    email: string;
}
export enum Duration {
    min15 = "min15",
    min30 = "min30",
    min45 = "min45",
    min60 = "min60"
}
export enum UserRole {
    admin = "admin",
    user = "user"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    invited = "invited"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    /**
     * / Set the base URL used in management links sent to clients.
     */
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    /**
     * / Get the current app base URL (for debugging).
     */
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptInvite(token: string): Promise<{
        __kind__: "ok";
        ok: UserView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelBooking(bookingId: string): Promise<boolean>;
    cancelBookingByToken(token: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    changeUserRole(email: string, role: UserRole): Promise<boolean>;
    createBooking(input: CreateBookingInput, busyIntervals: Array<BusyInterval>, appBaseUrl: string): Promise<BookingView>;
    createBookingLink(input: BookingLinkInput): Promise<BookingLinkView>;
    deleteBookingLink(linkId: string): Promise<boolean>;
    /**
     * / Set the base URL used in management links sent to clients.
     */
    fetchGoogleCalendarFreeBusy(calendarId: string, timeMin: string, timeMax: string): Promise<string>;
    /**
     * / Get the current app base URL (for debugging).
     */
    getAppBaseUrl(): Promise<string>;
    getAvailableSlots(linkId: string, rangeStart: bigint, rangeEnd: bigint, busyIntervals: Array<BusyInterval>): Promise<Array<TimeSlot>>;
    getBookingByToken(token: string): Promise<BookingView | null>;
    getBookingLink(linkId: string): Promise<BookingLinkView | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getGoogleCalendarCredentialStatus(): Promise<GoogleCredentialStatus>;
    getGoogleOAuthClientId(): Promise<string>;
    getMyUserInfo(): Promise<UserView | null>;
    getOverridesForLink(linkId: string): Promise<Array<BusyOverride>>;
    hasGoogleCalendarCredentials(): Promise<boolean>;
    inviteUser(input: InviteInput): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    listBookingLinks(): Promise<Array<BookingLinkView>>;
    listBookings(): Promise<Array<BookingView>>;
    listUsers(): Promise<Array<UserView>>;
    refreshGoogleCalendarCredentials(): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    removeUser(email: string): Promise<boolean>;
    rescheduleBookingByToken(token: string, newTimeSlotStart: bigint, newTimeSlotEnd: bigint, busyIntervals: Array<BusyInterval>, appBaseUrl: string): Promise<{
        __kind__: "ok";
        ok: BookingView;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Set the base URL used in management links sent to clients.
     */
    setAppBaseUrl(url: string): Promise<void>;
    setBookingLinkActive(linkId: string, isActive: boolean): Promise<boolean>;
    setGoogleCalendarCredentials(accessToken: string, refreshToken: string, expiresAt: bigint): Promise<void>;
    setGoogleOAuthClientId(clientId: string): Promise<void>;
    setHostPrincipal(p: Principal): Promise<void>;
    setUsersAppBaseUrl(url: string): Promise<void>;
    toggleBusyOverride(linkId: string, slotStart: bigint, slotEnd: bigint, isBookable: boolean): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBookingLink(linkId: string, input: BookingLinkInput): Promise<BookingLinkView | null>;
}
import type { BookingLinkInput as _BookingLinkInput, BookingLinkView as _BookingLinkView, BookingView as _BookingView, CreateBookingInput as _CreateBookingInput, Duration as _Duration, ExternalBlob as _ExternalBlob, GoogleCredentialStatus as _GoogleCredentialStatus, InviteInput as _InviteInput, UserRole as _UserRole, UserRole__1 as _UserRole__1, UserStatus as _UserStatus, UserView as _UserView, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptInvite(arg0: string): Promise<{
        __kind__: "ok";
        ok: UserView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptInvite(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptInvite(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async cancelBookingByToken(arg0: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBookingByToken(arg0);
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBookingByToken(arg0);
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async changeUserRole(arg0: string, arg1: UserRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: CreateBookingInput, arg1: Array<BusyInterval>, arg2: string): Promise<BookingView> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(await to_candid_CreateBookingInput_n21(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_BookingView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(await to_candid_CreateBookingInput_n21(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_BookingView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBookingLink(arg0: BookingLinkInput): Promise<BookingLinkView> {
        if (this.processError) {
            try {
                const result = await this.actor.createBookingLink(to_candid_BookingLinkInput_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BookingLinkView_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBookingLink(to_candid_BookingLinkInput_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BookingLinkView_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBookingLink(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBookingLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBookingLink(arg0);
            return result;
        }
    }
    async fetchGoogleCalendarFreeBusy(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGoogleCalendarFreeBusy(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGoogleCalendarFreeBusy(arg0, arg1, arg2);
            return result;
        }
    }
    async getAppBaseUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppBaseUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppBaseUrl();
            return result;
        }
    }
    async getAvailableSlots(arg0: string, arg1: bigint, arg2: bigint, arg3: Array<BusyInterval>): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getBookingByToken(arg0: string): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingByToken(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingByToken(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingLink(arg0: string): Promise<BookingLinkView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingLink(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingLink(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoogleCalendarCredentialStatus(): Promise<GoogleCredentialStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoogleCalendarCredentialStatus();
                return from_candid_GoogleCredentialStatus_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoogleCalendarCredentialStatus();
            return from_candid_GoogleCredentialStatus_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoogleOAuthClientId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoogleOAuthClientId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoogleOAuthClientId();
            return result;
        }
    }
    async getMyUserInfo(): Promise<UserView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUserInfo();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUserInfo();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverridesForLink(arg0: string): Promise<Array<BusyOverride>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverridesForLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverridesForLink(arg0);
            return result;
        }
    }
    async hasGoogleCalendarCredentials(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasGoogleCalendarCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasGoogleCalendarCredentials();
            return result;
        }
    }
    async inviteUser(arg0: InviteInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteUser(to_candid_InviteInput_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteUser(to_candid_InviteInput_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listBookingLinks(): Promise<Array<BookingLinkView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookingLinks();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookingLinks();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBookings(): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookings();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookings();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshGoogleCalendarCredentials(): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshGoogleCalendarCredentials();
                return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshGoogleCalendarCredentials();
            return from_candid_variant_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async rescheduleBookingByToken(arg0: string, arg1: bigint, arg2: bigint, arg3: Array<BusyInterval>, arg4: string): Promise<{
        __kind__: "ok";
        ok: BookingView;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleBookingByToken(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleBookingByToken(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAppBaseUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppBaseUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppBaseUrl(arg0);
            return result;
        }
    }
    async setBookingLinkActive(arg0: string, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setBookingLinkActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBookingLinkActive(arg0, arg1);
            return result;
        }
    }
    async setGoogleCalendarCredentials(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGoogleCalendarCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGoogleCalendarCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async setGoogleOAuthClientId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGoogleOAuthClientId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGoogleOAuthClientId(arg0);
            return result;
        }
    }
    async setHostPrincipal(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHostPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHostPrincipal(arg0);
            return result;
        }
    }
    async setUsersAppBaseUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsersAppBaseUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsersAppBaseUrl(arg0);
            return result;
        }
    }
    async toggleBusyOverride(arg0: string, arg1: bigint, arg2: bigint, arg3: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleBusyOverride(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleBusyOverride(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBookingLink(arg0: string, arg1: BookingLinkInput): Promise<BookingLinkView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingLink(arg0, to_candid_BookingLinkInput_n29(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingLink(arg0, to_candid_BookingLinkInput_n29(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingLinkView_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingLinkView): BookingLinkView {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_BookingView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingView): Promise<BookingView> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Duration_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Duration): Duration {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GoogleCredentialStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoogleCredentialStatus): GoogleCredentialStatus {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserView): UserView {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingView]): Promise<BookingView | null> {
    return value.length === 0 ? null : await from_candid_BookingView_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingLinkView]): BookingLinkView | null {
    return value.length === 0 ? null : from_candid_BookingLinkView_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserView]): UserView | null {
    return value.length === 0 ? null : from_candid_UserView_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    principal: [] | [string];
    name: string;
    createdAt: bigint;
    role: _UserRole;
    email: string;
}): {
    status: UserStatus;
    principal?: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
} {
    return {
        status: from_candid_UserStatus_n11(_uploadFile, _downloadFile, value.status),
        principal: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.principal)),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCancelled: boolean;
    managementToken: string;
    bookingId: string;
    clientName: string;
    createdAt: bigint;
    clientEmail: string;
    timeSlotStart: bigint;
    fileUrls: Array<_ExternalBlob>;
    timeSlotEnd: bigint;
    purpose: string;
    linkId: string;
}): Promise<{
    isCancelled: boolean;
    managementToken: string;
    bookingId: string;
    clientName: string;
    createdAt: bigint;
    clientEmail: string;
    timeSlotStart: bigint;
    fileUrls: Array<ExternalBlob>;
    timeSlotEnd: bigint;
    purpose: string;
    linkId: string;
}> {
    return {
        isCancelled: value.isCancelled,
        managementToken: value.managementToken,
        bookingId: value.bookingId,
        clientName: value.clientName,
        createdAt: value.createdAt,
        clientEmail: value.clientEmail,
        timeSlotStart: value.timeSlotStart,
        fileUrls: await from_candid_vec_n27(_uploadFile, _downloadFile, value.fileUrls),
        timeSlotEnd: value.timeSlotEnd,
        purpose: value.purpose,
        linkId: value.linkId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: _Duration;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
}): {
    id: string;
    duration: Duration;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        duration: from_candid_Duration_n35(_uploadFile, _downloadFile, value.duration),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [bigint];
    isExpired: boolean;
    hasCredentials: boolean;
}): {
    expiresAt?: bigint;
    isExpired: boolean;
    hasCredentials: boolean;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.expiresAt)),
        isExpired: value.isExpired,
        hasCredentials: value.hasCredentials
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    invited: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "invited" in value ? UserStatus.invited : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    min15: null;
} | {
    min30: null;
} | {
    min45: null;
} | {
    min60: null;
}): Duration {
    return "min15" in value ? Duration.min15 : "min30" in value ? Duration.min30 : "min45" in value ? Duration.min45 : "min60" in value ? Duration.min60 : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
async function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BookingView;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: BookingView;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_BookingView_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserView_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingLinkView>): Array<BookingLinkView> {
    return value.map((x)=>from_candid_BookingLinkView_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingView>): Promise<Array<BookingView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BookingView_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserView>): Array<UserView> {
    return value.map((x)=>from_candid_UserView_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BookingLinkInput_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingLinkInput): _BookingLinkInput {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateBookingInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBookingInput): Promise<_CreateBookingInput> {
    return await to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Duration_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Duration): _Duration {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_InviteInput_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InviteInput): _InviteInput {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clientName: string;
    clientEmail: string;
    timeSlotStart: bigint;
    fileUrls: Array<ExternalBlob>;
    timeSlotEnd: bigint;
    purpose: string;
    linkId: string;
}): Promise<{
    clientName: string;
    clientEmail: string;
    timeSlotStart: bigint;
    fileUrls: Array<_ExternalBlob>;
    timeSlotEnd: bigint;
    purpose: string;
    linkId: string;
}> {
    return {
        clientName: value.clientName,
        clientEmail: value.clientEmail,
        timeSlotStart: value.timeSlotStart,
        fileUrls: await to_candid_vec_n23(_uploadFile, _downloadFile, value.fileUrls),
        timeSlotEnd: value.timeSlotEnd,
        purpose: value.purpose,
        linkId: value.linkId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: Duration;
    name: string;
    description: string;
}): {
    duration: _Duration;
    name: string;
    description: string;
} {
    return {
        duration: to_candid_Duration_n31(_uploadFile, _downloadFile, value.duration),
        name: value.name,
        description: value.description
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
    email: string;
}): {
    name: string;
    role: _UserRole;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n19(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Duration): {
    min15: null;
} | {
    min30: null;
} | {
    min45: null;
} | {
    min60: null;
} {
    return value == Duration.min15 ? {
        min15: null
    } : value == Duration.min30 ? {
        min30: null
    } : value == Duration.min45 ? {
        min45: null
    } : value == Duration.min60 ? {
        min60: null
    } : value;
}
async function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
